### ISSUE TITLE
Cant install from eclipse market

### ISSUE THREAD

**Issue by bademux** [sputnikdev/eclipse-smarthome-bluetooth-binding#1]
Error whhile installing from EclipseMarket  "Binding cannot be installed: Error reading bundle content."
Openhab 2.2.0 stable
Bluetooth Binding market:binding-3694484 - 1.0

**Comment by vkolotov** [comment]
Thanks reporting this, but it is in its early stage so might not be working or links can be broken as snapshots versions are used. I'll let you know when it is ready for testing...

**Comment by bademux** [comment]
no problem, thanks for developing and sharing.

**Comment by vkolotov** [comment]
Hi @bademux, it is not available for betta testing if you are still keen. Please let me know how it goes.

**Comment by bademux** [comment]
thanks, I will try to test it on weekend,
