### ISSUE TITLE
add support for Playbulb Candle

### ISSUE THREAD

**Issue by maggu2810** [sputnikdev/eclipse-smarthome-bluetooth-binding#34]
Hi @vkolotov,
I would like to control my Playbulb Candle using your binding.

There is a Github project that contains some information about the protocol of that device e.g.:
* https://github.com/Phhere/Playbulb/blob/master/protocols/characteristics.md
* https://github.com/Phhere/Playbulb/blob/master/protocols/candle.md

Can you give me some the direction what is to do?

**Comment by vkolotov** [comment]
Hi @maggu2810, it seems to me it will be quite easy to add support for this device. Please have a look at some examples here:

https://github.com/sputnikdev/bluetooth-gatt-parser/blob/master/src/test/java/org/sputnikdev/bluetooth/gattparser/GenericCharacteristicParserIntegrationTest.java

and here

https://github.com/sputnikdev/bluetooth-gatt-parser/tree/master/src/main/resources/gatt/characteristic

Have a look how Oregon and Xiaomi devices have been implemented, it will give you an idea how to come up with GATT spec files for your device.

Also if you have time, could you please jump into this discussion?
https://github.com/sputnikdev/eclipse-smarthome-bluetooth-binding/issues/14#issuecomment-364748239

I'd like to get your opinion on that issue (authentication) and what is a good way to resolve it.

**Comment by vkolotov** [comment]
Forgot to mention this as well: https://github.com/sputnikdev/bluetooth-cli/tree/master/src/main/java/org/sputnikdev/bluetooth/examples

**Comment by maggu2810** [comment]
Sorry for the late response, but I realized that my Playbulb Candle doesn't seem to work reliable anymore.
Only the RED light seems to work.

So it is at least for me at the moment not very important to get the device working as it does not work anyway. If I buy a new one some time, I will have a look at it again.
