### ISSUE TITLE
Add support for nut mini

### ISSUE THREAD

**Issue by orzechszek** [sputnikdev/eclipse-smarthome-bluetooth-binding#36]
Hi,

Is it possible to add support for Nut mini bluetooth tracker?

**Comment by vkolotov** [comment]
Hi @orzechszek , I think so. Do you have any examples (any opensource projects)? If so, please add some references here.

**Comment by orzechszek** [comment]
Unfortunately not.. :/. I've just found it on aliexpress.

**Comment by vkolotov** [comment]
Have a look at iTag device on Aliexpress. It is similar and it is supported in the next release of the binding.

**Comment by orzechszek** [comment]
Nut mini is working - can be closed
